# jekyll config
# _drafts blog
# theme partly based on:
# Kiko-plus https://aweekj.github.io/Kiko-plus/ and Minima https://github.com/jekyll/minima

# basic
title: _drafts_framework
description: A framework for notes, blogs etcetera based on the _drafts carpentry off EvanWill.
keywords: framework, _drafts, EvanWill
author: EvanWill
github_username: Prudento-NL

url: https://Prudento-NL.github.io
baseurl: /_drafts_framework

# build
collections:
  notes:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
