# basic
title: framework-writings
description: A framework for all kinds of writings.
keywords: framework, writings
author: Kees
github_username: Prudento-NL
url: https://Prudento-NL.github.io
baseurl: /framework-writings

# build
collections:
  notes:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
